In [ ]:
import kagglehub
import pandas as pd
import os

# Download latest version
path = kagglehub.dataset_download("blastchar/telco-customer-churn")

print("Path to dataset files:", path)

# Find the CSV file in the downloaded path
csv_files = [f for f in os.listdir(path) if f.endswith('.csv')]
if csv_files:
    df = pd.read_csv(os.path.join(path, csv_files[0]))
    print(df.head())
else:
    print("No CSV file found in the dataset path.")

### Badanie Danych
- czyszczenie danych
- eksploracja danych
- poprawa typów danych

In [35]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [36]:
df.shape

(7043, 21)

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [38]:
# Wyświetlanie unikalnych wartości dla wszystkich kolumn
for col in df.columns:
    print(f"Kolumna: {col}")
    unique_vals = df[col].unique()
    
    # Jeśli wartości jest mało (< 50), pokaż wszystkie
    if len(unique_vals) < 50:
        print(unique_vals)
    else:
        # Jeśli dużo, pokaż licznik i pierwsze 10
        print(f"Zbyt wiele unikalnych wartości ({len(unique_vals)}). Pokazuję pierwsze 10:")
        print(unique_vals[:10])
    print("-" * 30)

Kolumna: customerID
Zbyt wiele unikalnych wartości (7043). Pokazuję pierwsze 10:
['7590-VHVEG' '5575-GNVDE' '3668-QPYBK' '7795-CFOCW' '9237-HQITU'
 '9305-CDSKC' '1452-KIOVK' '6713-OKOMC' '7892-POOKP' '6388-TABGU']
------------------------------
Kolumna: gender
['Female' 'Male']
------------------------------
Kolumna: SeniorCitizen
[0 1]
------------------------------
Kolumna: Partner
['Yes' 'No']
------------------------------
Kolumna: Dependents
['No' 'Yes']
------------------------------
Kolumna: tenure
Zbyt wiele unikalnych wartości (73). Pokazuję pierwsze 10:
[ 1 34  2 45  8 22 10 28 62 13]
------------------------------
Kolumna: PhoneService
['No' 'Yes']
------------------------------
Kolumna: MultipleLines
['No phone service' 'No' 'Yes']
------------------------------
Kolumna: InternetService
['DSL' 'Fiber optic' 'No']
------------------------------
Kolumna: OnlineSecurity
['No' 'Yes' 'No internet service']
------------------------------
Kolumna: OnlineBackup
['Yes' 'No' 'No internet service']
------------------------------
Kolumna: DeviceProtection
['No' 'Yes' 'No internet service']
------------------------------
Kolumna: TechSupport
['No' 'Yes' 'No internet service']
------------------------------
Kolumna: StreamingTV
['No' 'Yes' 'No internet service']
------------------------------
Kolumna: StreamingMovies
['No' 'Yes' 'No internet service']
------------------------------
Kolumna: Contract
['Month-to-month' 'One year' 'Two year']
------------------------------
Kolumna: PaperlessBilling
['Yes' 'No']
------------------------------
Kolumna: PaymentMethod
['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']
------------------------------
Kolumna: MonthlyCharges
Zbyt wiele unikalnych wartości (1585). Pokazuję pierwsze 10:
[ 29.85  56.95  53.85  42.3   70.7   99.65  89.1   29.75 104.8   56.15]
------------------------------
Kolumna: TotalCharges
Zbyt wiele unikalnych wartości (6531). Pokazuję pierwsze 10:
['29.85' '1889.5' '108.15' '1840.75' '151.65' '820.5' '1949.4' '301.9'
 '3046.05' '3487.95']
------------------------------
Kolumna: Churn
['No' 'Yes']
------------------------------

In [39]:
for col in df.columns:
    print(f"Kolumna: {col}")
    unique_vals = df[col].unique()
    
    # Jeśli wartości jest mało (< 50), pokaż wszystkie
    if len(unique_vals) < 5:
        df[col] = df[col].astype("category")

Kolumna: customerID
Kolumna: gender
Kolumna: SeniorCitizen
Kolumna: Partner
Kolumna: Dependents
Kolumna: tenure
Kolumna: PhoneService
Kolumna: MultipleLines
Kolumna: InternetService
Kolumna: OnlineSecurity
Kolumna: OnlineBackup
Kolumna: DeviceProtection
Kolumna: TechSupport
Kolumna: StreamingTV
Kolumna: StreamingMovies
Kolumna: Contract
Kolumna: PaperlessBilling
Kolumna: PaymentMethod
Kolumna: MonthlyCharges
Kolumna: TotalCharges
Kolumna: Churn

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   category
 2   SeniorCitizen     7043 non-null   category
 3   Partner           7043 non-null   category
 4   Dependents        7043 non-null   category
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   category
 7   MultipleLines     7043 non-null   category
 8   InternetService   7043 non-null   category
 9   OnlineSecurity    7043 non-null   category
 10  OnlineBackup      7043 non-null   category
 11  DeviceProtection  7043 non-null   category
 12  TechSupport       7043 non-null   category
 13  StreamingTV       7043 non-null   category
 14  StreamingMovies   7043 non-null   category
 15  Contract          7043 non-null   category
 16  PaperlessBilling  7043 non-null   category
 17  PaymentMethod     7043 non-null   category
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   category
dtypes: category(17), float64(1), int64(1), object(2)
memory usage: 339.4+ KB

In [41]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [42]:
df.TotalCharges = pd.to_numeric(df.TotalCharges, errors='coerce')

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   category
 2   SeniorCitizen     7043 non-null   category
 3   Partner           7043 non-null   category
 4   Dependents        7043 non-null   category
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   category
 7   MultipleLines     7043 non-null   category
 8   InternetService   7043 non-null   category
 9   OnlineSecurity    7043 non-null   category
 10  OnlineBackup      7043 non-null   category
 11  DeviceProtection  7043 non-null   category
 12  TechSupport       7043 non-null   category
 13  StreamingTV       7043 non-null   category
 14  StreamingMovies   7043 non-null   category
 15  Contract          7043 non-null   category
 16  PaperlessBilling  7043 non-null   category
 17  PaymentMethod     7043 non-null   category
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   category
dtypes: category(17), float64(2), int64(1), object(1)
memory usage: 339.4+ KB

In [44]:
df.TotalCharges.isna().sum()

np.int64(11)

In [45]:
df2 = df.dropna(subset=['TotalCharges'], inplace=False)

### Inżynieria cech
- One-hot encoding
- Label encoding

In [46]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7032 non-null   object
 1   gender            7032 non-null   category
 2   SeniorCitizen     7032 non-null   category
 3   Partner           7032 non-null   category
 4   Dependents        7032 non-null   category
 5   tenure            7032 non-null   int64
 6   PhoneService      7032 non-null   category
 7   MultipleLines     7032 non-null   category
 8   InternetService   7032 non-null   category
 9   OnlineSecurity    7032 non-null   category
 10  OnlineBackup      7032 non-null   category
 11  DeviceProtection  7032 non-null   category
 12  TechSupport       7032 non-null   category
 13  StreamingTV       7032 non-null   category
 14  StreamingMovies   7032 non-null   category
 15  Contract          7032 non-null   category
 16  PaperlessBilling  7032 non-null   category
 17  PaymentMethod     7032 non-null   category
 18  MonthlyCharges    7032 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7032 non-null   category
dtypes: category(17), float64(2), int64(1), object(1)
memory usage: 393.6+ KB

In [47]:
df2.head(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [30]:
def preprocess_telco_data(df):
    # Tworzymy kopię, żeby nie psuć oryginału
    df_processed = df.copy()
    
    # ---------------------------------------------------------
    # 1. ZMIENNE BINARNE (0 i 1)
    # ---------------------------------------------------------
    # Lista kolumn, które mają tylko 'Yes'/'No'
    binary_cols = ['Partner', 'Dependents', 'PhoneService', 
                   'PaperlessBilling', 'Churn']
    
    # Zamieniamy pętlą, bo logika jest ta sama
    for col in binary_cols:
        df_processed[col] = df_processed[col].map({'Yes': 1, 'No': 0})
        
    # Gender traktujemy oddzielnie (bo nie ma Yes/No)
    df_processed['gender'] = df_processed['gender'].map({'Female': 1, 'Male': 0})

    # ---------------------------------------------------------
    # 2. ZMIENNE PORZĄDKOWE (Ordinal)
    # ---------------------------------------------------------
    # Tu definiujemy hierarchię
    contract_mapping = {
        'Month-to-month': 0, 
        'One year': 1, 
        'Two year': 2
    }
    df_processed['Contract'] = df_processed['Contract'].map(contract_mapping)

    # ---------------------------------------------------------
    # 3. ZMIENNE NOMINALNE (One-Hot Encoding)
    # ---------------------------------------------------------
    # Lista kolumn, które nie mają kolejności, a mają więcej niż 2 opcje
    nominal_cols = ['PaymentMethod', 'InternetService', 'DeviceProtection', 
                    'TechSupport', 'StreamingTV', 'StreamingMovies', 
                    'OnlineBackup', 'OnlineSecurity', 'MultipleLines']
    
    # get_dummies robi nowe kolumny i usuwa stare. 
    # drop_first=True jest kluczowe (wyjaśnienie pod kodem)
    df_processed = pd.get_dummies(df_processed, 
                                  columns=nominal_cols, 
                                  drop_first=True, 
                                  dtype=int) # dtype=int wymusza 0/1 zamiast True/False
    
    return df_processed

In [48]:
df_clean = preprocess_telco_data(df2)
df_clean.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,Contract,PaperlessBilling,MonthlyCharges,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,OnlineBackup_No internet service,OnlineBackup_Yes,OnlineSecurity_No internet service,OnlineSecurity_Yes,MultipleLines_No phone service,MultipleLines_Yes
0,7590-VHVEG,1,0,1,0,1,0,0,1,29.85,...,0,0,0,0,0,1,0,0,1,0
1,5575-GNVDE,0,0,0,0,34,1,1,0,56.95,...,0,0,0,0,0,0,0,1,0,0
2,3668-QPYBK,0,0,0,0,2,1,0,1,53.85,...,0,0,0,0,0,1,0,1,0,0
3,7795-CFOCW,0,0,0,0,45,0,1,0,42.30,...,0,0,0,0,0,0,0,1,1,0
4,9237-HQITU,1,0,0,0,2,1,0,1,70.70,...,0,0,0,0,0,0,0,0,0,0

In [50]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 31 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   customerID                             7032 non-null   object
 1   gender                                 7032 non-null   category
 2   SeniorCitizen                          7032 non-null   category
 3   Partner                                7032 non-null   category
 4   Dependents                             7032 non-null   category
 5   tenure                                 7032 non-null   int64
 6   PhoneService                           7032 non-null   category
 7   Contract                               7032 non-null   category
 8   PaperlessBilling                       7032 non-null   category
 9   MonthlyCharges                         7032 non-null   float64
 10  TotalCharges                           7032 non-null   float64
 11  Churn                                  7032 non-null   category
 12  PaymentMethod_Credit card (automatic)  7032 non-null   int64
 13  PaymentMethod_Electronic check         7032 non-null   int64
 14  PaymentMethod_Mailed check             7032 non-null   int64
 15  InternetService_Fiber optic            7032 non-null   int64
 16  InternetService_No                     7032 non-null   int64
 17  DeviceProtection_No internet service   7032 non-null   int64
 18  DeviceProtection_Yes                   7032 non-null   int64
 19  TechSupport_No internet service        7032 non-null   int64
 20  TechSupport_Yes                        7032 non-null   int64
 21  StreamingTV_No internet service        7032 non-null   int64
 22  StreamingTV_Yes                        7032 non-null   int64
 23  StreamingMovies_No internet service    7032 non-null   int64
 24  StreamingMovies_Yes                    7032 non-null   int64
 25  OnlineBackup_No internet service       7032 non-null   int64
 26  OnlineBackup_Yes                       7032 non-null   int64
 27  OnlineSecurity_No internet service     7032 non-null   int64
 28  OnlineSecurity_Yes                     7032 non-null   int64
 29  MultipleLines_No phone service         7032 non-null   int64
 30  MultipleLines_Yes                      7032 non-null   int64
dtypes: category(8), float64(2), int64(20), object(1)
memory usage: 1.3+ MB